
/*

   Autogenerated by CAP duplicate fixer v1.0.0 at 18-04-2022 11:20:17.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test-suite/src/test/java/io/micronaut/docs/server/response/ProducesControllerSpec.java , [40:9~42:64]
   test-suite/src/test/java/io/micronaut/docs/datavalidation/params/EmailControllerSpec.java , [41:9~43:64]
   test-suite/src/test/java/io/micronaut/docs/server/response/StatusControllerSpec.java , [42:9~44:64]
   test-suite/src/test/java/io/micronaut/docs/datavalidation/pogo/EmailControllerSpec.java , [42:9~44:64]
   test-suite/src/test/java/io/micronaut/docs/server/consumes/ConsumesControllerSpec.java , [40:9~42:64]

*/


package io.micronaut.docs;

import io.micronaut.http.client.HttpClient;
import io.micronaut.runtime.server.EmbeddedServer;

public final class ExtractedSeparateClass21111 {
    private ExtractedSeparateClass21111() {
        throw new UnsupportedOperationException("This class cannot be instantiated");
    }
    
    public static HttpClient getClient11688(final EmbeddedServer server) {
        
        return server
                    .getApplicationContext()
                    .createBean(HttpClient.class, server.getURL());
    }
}
